myproject/myapp/urls.py
from django.contrib import admin
from django.urls import path
from myapp import views
from .views import *


app_name = 'myapp'

urlpatterns = [

    path('', views.Home, name='Home'),
    # path('bestseller/', views.bestseller, name='bestseller'),
    # path('new/', views.new, name='new'),


    path('productdetail/', views.productdetail, name='productdetail'),
    # path('product-detail/<id>/', views.products, name='product_detail'),
    # path('product/<int:pk>/', views.products, name='product_detail'),

    path('products/', views.products, name='products'),
   
    # path('products/<slug>', ProductsView.as_view(), name='products'),

    path('about/', views.about, name='about'),

    path('acc/', views.account, name='account'),
    path('register/', views.reg, name='Reg'),
    path('login/', views.login, name='Login'),


    path('order/', views.Order, name='order'),
    path('add-to-cart/<int:pk>', views.add_to_cart_view,name='add-to-cart'),
    path('remove-from-cart/<int:pk>', views.remove_from_cart_view,name='remove-from-cart'),
    path('address', views.address,name='address'),

    path('payment/', views.payment, name='payment'),

    path('refund/', views.refund, name='refund'),
    path('refund/linktr.ee/Phefluffy', views.refund, name='refund'),

    # path('get_image_urls/', get_image_urls, name='get_image_urls'),
    

    # path('orderplace/', views.)
    # path('top/', views.top, name='top'),


]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from myapp import views
from myapp.views import *



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
    # path('login/', views.login,name='Login'),
    # path('reg/', views.reg, name='Reg'),
    
]

from django.conf import settings
from django.conf.urls.static import static
urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

myproject/myapp/forms.py
from django import forms 
from myapp.models import *
from django.forms.fields import EmailField 
from django.contrib.auth.models import User
from crispy_forms.helper import FormHelper
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


class LoginForm(forms.Form): 
   username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Username'}))
   password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))

   class Meta:
        model = User
        fields = ('username', 'password')

   def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_show_labels = False
   
# class RegForm(forms.Form):
#    Username = forms.CharField(max_length=100) 
#    Email = forms.EmailField(required=True)
#    Password = forms.CharField(max_length=100)

class RegForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'First name'}))
    surname = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Last name'}))
    phone = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Phone number'}))
    address = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Address'}))
    email = forms.CharField(widget=forms.EmailInput(attrs={'placeholder': 'Email'}))
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Username'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))

    class Meta:
        model = User
        fields = [('username', 'email', 'first_name', 'last_name', 'password1', 'password2')]

    def __init__(self, *args, **kwargs):
        super(RegForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_show_labels = False

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError(
                "Customer with this useername already exists")
        

class AddressForm(forms.Form):
   Name = forms.CharField(max_length=200)
   Email = forms.EmailField(required=True)
   Mobile= forms.IntegerField(required=True)
   Address = forms.CharField(max_length=500)

myproject/myapp/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from .forms import *
from .forms import LoginForm, RegForm, AddressForm
from django.contrib import messages
from django.conf import settings
from django.contrib.auth.models import Group
from django.http import HttpResponse
from django.views.generic import DetailView, ListView, CreateView, FormView, View
from myapp.models import *
from django.urls import reverse_lazy
from django.contrib.auth import authenticate, login, logout
from myapp.models import Product
import os
import libscrc
import qrcode


# def login(request):
#    if request.method == "POST": 
#        Login = Login(request.POST) 
#        Login =forms.LoginForm(request.POST, request.FILES)
#        if Login.is_valid(): 
            
#             print('Username:', Login.cleaned_data['Username'])
#             print('Password:',Login.cleaned_data['Password'])
            
#             return redirect('products')
#    else: 
#        Login = LoginForm() 
       
#    return render(request, "home.html", {'Login':login})

# class LoginView(View):
#     def get(self, request):
#         logout(request)
#         return redirect('home')

class LoginView(FormView):
    template_name = 'login.html'
    form_class = LoginForm
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        username = form.cleaned_data.get('username')
        password = form.cleaned_data["password"]
        usr = authenticate(username=username, password=password)
        if usr is not None and Customer.objects.filter(user=usr).exists():
            login(self.request, usr)
        else:
            return render(self.request, self.template_name, {"form": self.form_class, "error": "Invalid credentials"})
        return super().form_valid(form)

    def get_success_url(self):
        if "next" in self.request.GET:
            next_url = self.request.GET.get("next")
            return next_url
        else:
            return self.success_url
        
    def login(request):
        if request.method == "POST": 
            Login = Login(request.POST) 
            Login =forms.LoginForm(request.POST, request.FILES)
            if Login.is_valid(): 
                    
                    print('Username:', Login.cleaned_data['Username'])
                    print('Password:',Login.cleaned_data['Password'])
                    
                    return redirect('products')
        else: 
            Login = LoginForm() 
            
        return render(request, "home.html", {'Login':login})


def reg(request):
   if request.method == "POST": 
       Reg = Reg(request.POST) 
       Reg =forms.RegForm(request.POST, request.FILES)
       if Reg.is_valid(): 
            print('Username:', Reg.cleaned_data['Username'])
            print('Email:', Reg.cleaned_data['Email']) 
            print('Password:',Reg.cleaned_data['Password'])
            
            return redirect('products')
   else: 
       Reg = RegForm() 

   return render(request, "products.html", {'RegForm':reg})

class regView(CreateView):
    template_name = 'register.html'
    form_class = RegForm
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        email = form.cleaned_data.get('email')
        user = User.objects.create_user(username, email, password)
        form.instance.user = user
        login(self.request, user)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('home')


def Home(request):
    return render(request,'home.html', {'Home':Home})


def about(request):
    return render(request, "about.html", {'about':about})

def account(request):
    return render(request, "account.html", {'account':account})

def payment(request):
    return render(request, "payment.html", {'payment':payment})

def refund(request):
    return render(request,'refund.html',{'refund':refund})
# class ProductDetailView(DetailView):
#     model = Product
#     template_name = "productdetail.html"

# class ProductDetailView(DetailView):
#     model = Product
#     template_name = 'productdetail.html'

    def get_object(self, queryset=None):
        if queryset is None:
            queryset = self.get_queryset()

        # # fetch the object based on a different identifier, e.g. the product code
        # product_code = self.kwargs.get('id')
        # obj = get_object_or_404(queryset, id = product_code)
        # return obj

def productdetail(request):
    # productdetail = get_object_or_404(Product, id=1)
    # if 'product_title' in request.COOKIES:            
    #     product_title = request.COOKIES['product_title']
    #     counter = product_title.split('|')
    #     product_count_in_cart = len(set(counter))
    # else:
    #     product_count_in_cart = 0
    #     context = {
    #     'p': productdetail,
    #     'product_count_in_cart': product_count_in_cart,}
    return render(request, "productdetail.html",  {'productdetail':productdetail})


# class Products(ListView):
#     model = Product
#     template = 'products_list.html'

def products(request):
    products = Product.objects.all()
    context = {'products': products}
    return render(request, 'product_list.html', context)

# def products(request):
#     products = models.Product.objects.all()

    # for p in products:
    #     print(p.title)


    # if 'product_title' in request.COOKIES:
    #     product_title = request.COOKIES['product_title']
    #     counter = product_title.split('|')
    #     product_count_in_cart=len(set(counter)) 

    # else:
    #     product_count_in_cart = 0
    #     context = {
    #     'p': products,
    #     'product_count_in_cart': product_count_in_cart,}
    # # if request.user.is_authenticated:
    #     return HttpResponseRedirect('Products')
    # return render(request,'products_list.html', {'products':products,'product_count_in_cart':product_count_in_cart})


# def top(request):
#     top = models.top.objects.all()
#     if 'tops' in request.COOKIES:
#         tops = request.COOKIES['tops']

#     if request.user.is_authenticated:
#         return HttpResponseRedirect('top')
#     return render(request, "top.html", {'top':top})

# def logout(request):
#     return render(request, "logout.html", {'logout':logout})


# def bestseller(request):
#     bestseller = models.bestseller.object.all()
#     if request.user.is_autheticated:
#         return HttpResponseRedirect('bestseller')
#     return render(request, "home.html", {'bestseller':bestseller})


# def new(request):
#     new = models.new.object.all()
#     if 'new' in request.COOKIES:
#         new = request.COOKIES['new']

#     if request.user.is_autheticated:
#         return HttpResponseRedirect('new')
#     return render(request, "home.html", {'new':new})


def add_to_cart_view(request,pk):
    products = models.Product.objects.all()

    if 'product_title' in request.COOKIES:
        product_title = request.COOKIES['product_title']
        counter = product_title.split('|')
        product_count_in_cart=len(set(counter))
    else:
        product_count_in_cart=1

    response = render(request, 'home.html',{'products':products,'product_count_in_cart':product_count_in_cart})
    # response = render(request, 'homepage.html',{'products':products,'product_count_in_cart':product_count_in_cart,'redirect_to' : request.GET['next_page']})

    if 'product_title' in request.COOKIES:
        product_title = request.COOKIES['product_title']
        if product_title =="":
            product_title = str(pk)
        else:
            product_title = str(product_title)+"|"+str(pk)
        response.set_cookie('product_title', product_title)
        
    else:
        product_title = pk
        response.set_cookie('product_title', pk)
  

    product = models.Product.objects.get(id=pk)
    messages.info(request, product.title)

    return response


def Order(request):
    if 'product_title' in request.COOKIES:
        product_title = request.COOKIES['product_title']
        counter = product_title.split('|')
        product_count_in_cart=len(set(counter))
    else:
        product_count_in_cart=0

    products=None
    total=0
    if 'product_title' in request.COOKIES:
        product_title = request.COOKIES['product_title']
        if product_title != "":
            product_id_in_cart = product_title.split('|')
            products = models.Product.objects.all().filter(id__in = product_id_in_cart)

            for p in products:
                total = total+ p.selling_price
    return render(request,'order.html',{'products':products,'total':total,'product_count_in_cart':product_count_in_cart})


def remove_from_cart_view(request,pk):
    if 'product_title' in request.COOKIES:
        product_title = request.COOKIES['product_title']
        counter=product_title.split('|')
        product_count_in_cart=len(set(counter))
    else:
        product_count_in_cart=0

    total=0
    if 'product_title' in request.COOKIES:
        product_title = request.COOKIES['product_title']
        product_id_in_cart=product_title.split('|')
        product_id_in_cart=list(set(product_id_in_cart))
        product_id_in_cart.remove(str(pk))
        products=models.Product.objects.all().filter(id__in = product_id_in_cart)
        for p in products:

            total = total+ p.selling_price

        value=""
        for i in range(len(product_id_in_cart)):
            if i==0:
                value=value+product_id_in_cart[0]
            else:
                value=value+"|"+product_id_in_cart[i]
        response = render(request, 'cart.html',{'products':products,'total':total,'product_count_in_cart':product_count_in_cart,'redirect_to' : request.GET['next_page']})
        if value=="":
            response.delete_cookie('product_title')

myproject/myapp/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width", initial-scale="1.0">
        <title> PHEFLUFFY Official</title>
        <link rel="stylesheet" href="{% static 'style.css'%}">
        <link rel="stylesheet" href="{% static 'images/MagicEraser_5660418_164818.PNG'%}">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=DM+Serif+Display&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.2.1/css/fontawesome.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0">
        

    </head>
    <body>
        
        <div class="header">

            <div class="containner">
                <div class="navbar">
                    <div class="logo">
                        <a href="{% url 'myapp:Home'%}">
                        <img src="{% static 'images/MagicEraser_5660418_164818.PNG' %}" width="125px"></a>
                    </div>
                    <nav>
                        <ul id="MenuItems">
                            <li><a href="{% url 'myapp:Home'%}">Home</a></li>
                            <li><a href="{% url 'myapp:products'%}">Products</a></li>
                            <li><a href="{% url 'myapp:about'%}">About</a></li>
                            <li><a href="{% url 'myapp:account'%}">Account</a></li>
                        </ul>
                    </nav>
                    <a href="{% url 'myapp:order'%}">
                    <img src="https://cdn-icons-png.flaticon.com/512/1413/1413908.png" width="30px" height="30px" class="cart-img"></a>
                    <img src="{% static 'images/menu_FILL0_wght400_GRAD0_opsz40.png' %}" class="menu-icon" onclick="menutoggle()">
                </div>
                
                <div class="row">
                    <div class="col-2">
                        <h1>Let's go baby</h1>
                        <p>“Discover your style and elevate your wardrobe with just a click”</p>
                        <a href="{% url 'myapp:products' %}" class="btn">Click!</a>
                    </div>
                </div>
                
            </div>
        </div>
<!-- ------- promotion -------- -->
            <div class="promotion">
                <div class="small-container">
                
                    <div class="row">
                        <div class="col-3">
                            <img src="{% static 'images/S__55623699.jpg'%}">
                        </div>
                        <div class="col-3">
                            <img src="{% static 'images/S__55623700.jpg' %}">
                        </div>
                        <div class="col-3">
                            <img src="{% static 'images/S__55623701.jpg' %}">
                        </div> 
                    </div>
                    
                </div>
            </div>

<!-- ----------featured Products------------ -->

             <div class="small-container">
                <h2 class="title">Best Seller</h2>

                {% comment %} {% for p in produc %} {% endcomment %}
                <div class="row">
                    <div class="col-4">
                        <img src="https://d.line-scdn.net/obs/r/ect/ect/image_165577979268402309819cc5425t0fed58c0">
                        <h4>Semi pants (Black)</h4>
                        <p>390</p>
                    </div>
                
                    <div class="col-4">
                        <img src="https://d.line-scdn.net/obs/r/ect/ect/image_164915288154689336619c92043t0f883a61">
                        <h4>Fluffy short pants (Cream)</h4>
                        <p>250 ฿</p>
                    </div>
                    <div class="col-4">
                        <img src="https://obs.line-scdn.net/r/ect/ect/image_165335775119581928219cb4124t0fc863a7">
                        <h4>Gummy pants (Light blue)</h4>
                        <p>300 ฿</p>
                    </div>
                    <div class="col-4">
                        <img src="https://obs.line-scdn.net/r/ect/ect/image_164412334886391344819ca9849t0f3b7bc4">
                        <h4>Red rose T-shirt</h4>
                        <p>300 ฿</p>
                    </div>
                </div>
                

                <h2 class="title">New Arrivals</h2>

                {% comment %} {% for p in product%} {% endcomment %}
                <div class="row">
                    <div class="col-4">
                        <img src="{% static 'images/LINE_P25660425_124142133.png'%}">
                        <h4>Gummy pants (White)</h4>
                        <p>320 ฿</p>
                    </div>
                    <div class="col-4">
                        <img src="{% static 'images/Image 19-4-2566 BE at 15.22 (2).jpg'%}">
                        <h4>Tiny top (Blue)</h4>
                        <p>250 ฿</p>
                    </div>
                    <div class="col-4">
                        <img src="{% static 'images/Image 19-4-2566 BE at 15.24 (1).jpg'%}">
                        <h4>Jelly shorts (Black)</h4>
                        <p>260 ฿</p>
                    </div>
                    <div class="col-4">
                        <img src="{% static 'images/IKBUKNQOW9ZPZPCWTUMXVITGN81NU5.jpeg'%}">
                        <h4>Cool girl crop (Black)</h4>
                        <p>139 ฿</p>
                    </div>
                    <div class="col-4">
                        <img src="{% static 'images/image_164826821992954093719d03061t0f7abaab.jpeg'%}">
                        <h4>Choco teddy crop</h4>
                        <p>270 ฿</p>
                    </div>
                    <div class="col-4">
                        <img src="{% static 'images/Image 19-4-2566 BE at 15.24 (2).jpg'%}">
                        <h4>Tennis skirt (White)</h4>
                        <p>260 ฿</p>
                    </div>
                    <div class="col-4">
                        <img src="{% static 'images/Image 19-4-2566 BE at 15.22.jpg'%}">
                        <h4>Judy crop (Brownie)</h4>
                        <p>250 ฿</p>
                    </div>
                    <div class="col-4">
                        <img src="{% static 'images/image_164921569876900746319c99284t0f892fc2.jpeg'%}">
                        <h4>Love me love my cat crop</h4>
                        <p>270 ฿</p>
                    </div>
                </div>
                {% comment %} {% endfor %} {% endcomment %}
             </div>
<!-- --------- offer--------- -->
            <div class="offer">
                <div class="small-container">
                    <div class="row">
                        <div class="col-2">
                            <img src="https://d.line-scdn.net/obs/r/ect/ect/image_164238751406681032019cd4890t0f20ff2a" class="offer-img"> 
                        </div>
                        <div class="col-2-detail">
                            <p>Exclusively Available on PHEFLUFFY</p>
                            <h1>Mandarin collar</h1>
                            <small>and roller coaster kinda rush and i never knew i could feel that much and that's the way i loved you</small>
                            <br>
                            <a href="{% url 'myapp:productdetail'%}">Buy Now &#8594;</a>
                        </div>
                    </div>
                </div>
            </div>

<!-- -------- testimonial ------
            <div class="testimonial">
                <div class="small-container">
                    <div class="col-3">
                        <p>I miss your tan skin your sweet smile so good to me so right and how you held me in your arms that september night the first time you ever saw me cry</p>
                    </div>
                </div>
            </div>
------ brands ------ 
            <div class="brands">
                <div class="small-container">
                    <div class="row">
                        <div class="col-5">
                            <img src="" alt="">
                        </div>
                        <div class="col-5">
                            <img src="" alt="">
                        </div>
                        <div class="col-5">
                            <img src="" alt="">
                        </div>
                        <div class="col-5">
                            <img src="" alt="">
                        </div>
                    </div>
                </div>
            </div> -->
<!-- -----footer---- -->
            <section id="footer">
                <img src="{% static 'images/MagicEraser_5660418_164818.PNG' %}" class="footer-img">
                <div class="title-text">
                <p>Contact us</p>
                </div>
            <div class="footer-row">
            <div class="footer-left">
                <h1>Account</h1>
                <a href="{% url 'myapp:account'%}"><p>Login</p></a>
                <a href="{% url 'myapp:account'%}"><p>Register</p></a>
            </div>
            <div class="footer-right">
                <h1>Get In Touch</h1>
                <p>address</p>
                <p>email</p>
                <p>tel</p>
            </div>
            </div>

            <div class="social-links">
                <a href="https://www.facebook.com/Phefluffy-110994267269264/"><i class="fa-brands fa-square-facebook fa-xl"></i></a>
                <a href="https://www.instagram.com/phefluffy/"><i class="fa-brands fa-instagram fa-xl"></i></a>
                <a href="https://shop.line.me/@317lcvbv"><i class="fa-brands fa-line fa-xl"></i></a>
                <p>Copyright - PHEFLUFFY Officials</p>
            </div>

            </section>
<!-- ---------js for toggle menu ---------- -->
            <script>
                var MenuItems = document.getElementById("MenuItems");

                MenuItems.style.maxHeight = "0px"

                function menutoggle(){
                    if(MenuItems.style.maxHeight = "0px")
                    {
                        MenuItems.style.maxHeight = "200px";
                    }
                    else
                    {
                        MenuItems.style.maxHeight = "0px";
                    }
                }
            </script>
        <script src="script.js"></script>
    </body>
</html>

myproject/myapp/templates/order.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width", initial-scale="1.0">
        <title> PHEFLUFFY Official</title>
        <link rel="stylesheet" href="{% static 'style.css'%}">
        <link rel="stylesheet" href="{% static 'images/MagicEraser_5660418_164818.PNG'%}">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=DM+Serif+Display&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.2.1/css/fontawesome.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0">
        <link rel="stylesheet" href="https://fontawesome.com/icons/trash?f=classic&s=light">

    </head>
    <body>
        
        <div class="header">

            <div class="containner">
                <div class="navbar">
                    <div class="logo">
                        <a href="{% url 'myapp:Home'%}">
                        <img src="{% static 'images/MagicEraser_5660418_164818.PNG' %}" width="125px"></a>
                    </div>
                    <nav>
                        <ul id="MenuItems">
                            <li><a href="{% url 'myapp:Home'%}">Home</a></li>
                            <li><a href="{% url 'myapp:products'%}">Products</a></li>
                            <li><a href="{% url 'myapp:about'%}">About</a></li>
                            <li><a href="{% url 'myapp:account'%}">Account</a></li>
                        </ul>
                    </nav>
                    <a href="{% url 'myapp:order'%}">
                    <img src="https://cdn-icons-png.flaticon.com/512/1413/1413908.png" width="30px" height="30px" class="cart-img"></a>
                    <img src="{% static 'images/menu_FILL0_wght400_GRAD0_opsz40.png' %}" class="menu-icon" onclick="menutoggle()">
                </div>
                
            </div>
        </div>


{% comment %} -------------------------------------------------------- {% endcomment %}

    <section class="order">
        <div class="small-container">
            <div class="row row-2">
                <h2>Order</h2>
            </div>

            {% for o in order %}
            {% if o %}
            <div class="small-container order">
                <div class="row">
                    <div class="orderitems">
                        <div>
                            <img src="{{ p.product_image }}" class="img-order">

                            <div class="orderdetail">
                                <p>{{ o.product }}</p>
                                <p>{{ o.selling_price }}</p>
                                <P>{{ o.quantity }}</p>
                                <P>{{ o.product_image }}</p>


                            </div>

                        </div>

                        {% comment %} <div>
                            <p>{{ p.category }}</p>
                        </div> {% endcomment %}
                        <div>
                            <a href="{% url 'myapp:remove-from-cart' p.id  %}?next_page={{request.path}}"> Delete </a>
                        </div>
                
            {%endif%}
            {%endfor%}

                <!-- <div class="col-lg-4 col-xl-3"> -->

                        {% comment %} <div class="subtptal" style="font-weight: 500;">
                            <p>Subtotal</p>
                            <p>฿{{ total }}</p>
                        </div> {% endcomment %} 

                    <div class='col-2-order'>
                        <img src="{% static 'images/Image 19-4-2566 BE at 11.38.jpg' %} " id='order-img'>
                            
                        <div class='man'>
                             
                            <p>Mandarin collar </p>
                            <p class='quan'>1</p>
                            <p class='price'>฿ 215</p>

                        </div>

                        <img src="{% static 'images/messageImage_1682068085855.jpg' %} " id='order-img'>
                        <hr/>
                        <div class='man'>
                            
                            <p>Semi pants(white)</p>
                            <p class='quan'>1</p>
                            <p class='price'>฿ 390</p>

                        </div>
                     

                    </div>
                    
                    <div class="totalprice">
                        <p>Total Price</p>
                        <p>฿ 605</p>
                    </div>

                    <a href="{% url 'myapp:payment'%}">
                    <button type="button" class="btn">
                        <div class="confirm">
                            <span>Confirm</span>
                        </div>
                    </button>
                    </a>

                    
            </div>
        </div>
    </section>
            

{% comment %} ------------------------------------------------------- {% endcomment %}

            <section id="footer">
                <img src="{% static 'images/MagicEraser_5660418_164818.PNG' %}" class="footer-img">
                <div class="title-text">
                <p>Contact us</p>
                </div>
            <div class="footer-row">
            <div class="footer-left">
                <h1>Account</h1>
                <a href="{% url 'myapp:account'%}"><p>Login</p></a>
                <a href="{% url 'myapp:account'%}"><p>Register</p></a>
            </div>
            <div class="footer-right">
                <h1>Get In Touch</h1>
                <p>address</p>
                <p>email</p>
                <p>tel</p>
            </div>
            </div>

            <div class="social-links">
                <a href="https://www.facebook.com/Phefluffy-110994267269264/"><i class="fa-brands fa-square-facebook fa-xl"></i></a>
                <a href="https://www.instagram.com/phefluffy/"><i class="fa-brands fa-instagram fa-xl"></i></a>
                <a href="https://shop.line.me/@317lcvbv"><i class="fa-brands fa-line fa-xl"></i></a>
                <p>Copyright - PHEFLUFFY Officials</p>
            </div>

            </section>

    </body>
</html>